name: Ritik's Medium
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-articles:
    name: Update this repo's README with Ritik's latest articles from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.2.5
        with:
          comment_tag_name: "ARTICLES"
          feed_list: "https://medium.com/feed/@ritikk"